### ISSUE TITLE
step-14 sagfaults in release mode

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#16384]
```
Refinement cycle: 5
   Number of degrees of freedom: 1665
   Point value: 0.0334083
   Estimated error: -0.221358
Refinement cycle: 6
free(): invalid pointer

Thread 1 "step-14.release" received signal SIGSEGV, Segmentation fault.
tcache_get (tc_idx=<optimized out>) at malloc.c:2937
2937    malloc.c: No such file or directory.
(gdb) bt
#0  tcache_get (tc_idx=<optimized out>) at malloc.c:2937
#1  __GI___libc_malloc (bytes=72) at malloc.c:3051
#2  0x00007fffe8fa470c in operator new(unsigned long) () from /lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007fffef635e65 in std::vector<std::vector<dealii::FullMatrix<double>, std::allocator<dealii::FullMatrix<double> > >, std::allocator<std::vector<dealii::FullMatrix<double>, std::allocator<dealii::FullMatrix<double> > > > >::vector(std::vector<std::vector<dealii::FullMatrix<double>, std::allocator<dealii::FullMatrix<double> > >, std::allocator<std::vector<dealii::FullMatrix<double>, std::allocator<dealii::FullMatrix<double> > > > > const&) ()
   from /ssd/deal-git/build/lib/libdeal_II.so.9.6.0-pre
#4  0x00007fffef79607d in dealii::FE_Poly<2, 2>::FE_Poly(dealii::FE_Poly<2, 2> const&) ()
   from /ssd/deal-git/build/lib/libdeal_II.so.9.6.0-pre
#5  0x00007fffef815bd6 in dealii::FE_Q<2, 2>::clone() const () from /ssd/deal-git/build/lib/libdeal_II.so.9.6.0-pre
#6  0x00007ffff6cc4e69 in dealii::hp::FECollection<2, 2>::push_back(dealii::FiniteElement<2, 2> const&) ()
   from /ssd/deal-git/build/lib/libdeal_II.so.9.6.0-pre
#7  0x00007ffff6cc4ff1 in dealii::hp::FECollection<2, 2>::FECollection(dealii::FiniteElement<2, 2> const&) ()
   from /ssd/deal-git/build/lib/libdeal_II.so.9.6.0-pre
#8  0x00007ffff4bcddaf in dealii::DoFHandler<2, 2>::distribute_dofs(dealii::FiniteElement<2, 2> const&) ()
   from /ssd/deal-git/build/lib/libdeal_II.so.9.6.0-pre
#9  0x00005555555f9682 in Step14::LaplaceSolver::Solver<2>::solve_problem() ()
#10 0x00005555555be3da in tbb::internal::function_task<dealii::Threads::Task<void>::Task(std::function<void ()> const&)::{lambda()#1}>::execute() ()
#11 0x00007fffe9340545 in ?? () from /lib/x86_64-linux-gnu/libtbb.so.2
#12 0x00007fffe934080f in ?? () from /lib/x86_64-linux-gnu/libtbb.so.2
#13 0x00005555555d5a52 in Step14::LaplaceSolver::WeightedResidual<2>::solve_problem() ()
#14 0x00005555555fb5c3 in Step14::Framework<2>::run(Step14::Framework<2>::ProblemDescription const&) ()
#15 0x00005555555f395c in main ()
```

**Comment by tjhei** [comment]
Similar to #16383, only appears with 4+ threads.

**Comment by bangerth** [comment]
Is this still a problem for you, @tjhei ? It seems to work for me.

**Comment by drwells** [comment]
I don't think we will be able to reproduce this - lets close this for now.
