### ISSUE TITLE
Link-time optimization issues.

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#17718]
I was curious to see what happens if I switch on link-time optimization by just adding `-flto` to the release build flags. First, I get linker errors as follows:
```
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:373:3: warning: type 'struct NumericType' violates the C++ One Definition Rule [-Wodr]
  373 | } NumericType ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:373:3: note: a different type is defined in another translation unit
  373 | } NumericType ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:340:10: note: the first difference of corresponding definitions is field 'D'
  340 |         *D ;            /* D [i] is the diagonal entry of U */
      |          ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:340:10: note: a field of same name but different type is defined in another translation unit
  340 |         *D ;            /* D [i] is the diagonal entry of U */
      |          ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:373:3: note: type 'double' should match type 'struct DoubleComplex'
  373 | } NumericType ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_version.h:181:3: note: the incompatible type is defined here
  181 | } DoubleComplex ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:638:3: warning: type 'struct WorkType' violates the C++ One Definition Rule [-Wodr]
  638 | } WorkType ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:638:3: note: a different type is defined in another translation unit
  638 | } WorkType ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:498:12: note: the first difference of corresponding definitions is field 'Wx'
  498 |     Entry *Wx, *Wy ;    /* each of size maxnrows+1 */
      |            ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:498:12: note: a field of same name but different type is defined in another translation unit
  498 |     Entry *Wx, *Wy ;    /* each of size maxnrows+1 */
      |            ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_internal.h:638:3: note: type 'double' should match type 'struct DoubleComplex'
  638 | } WorkType ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/umf_version.h:181:3: note: the incompatible type is defined here
  181 | } DoubleComplex ;
      |   ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/include/deal.II/lac/lapack_templates.h:387: warning: 'zgemv_' violates the C++ One Definition Rule [-Wodr]
  387 |   void DEAL_II_FORTRAN_MANGLE(zgemv,
      | 
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:195:6: note: type mismatch in parameter 1
  195 | void BLAS_ZGEMV (char *trans, BLAS_INT *m, BLAS_INT *n, double *alpha,
      |      ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:195:6: note: type 'char' should match type 'const char'
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:195:6: note: 'zgemv_' was previously declared here
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:195:6: note: code may be misoptimized unless '-fno-strict-aliasing' is used
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/include/deal.II/lac/lapack_templates.h:334: warning: 'zgemm_' violates the C++ One Definition Rule [-Wodr]
  334 |   void DEAL_II_FORTRAN_MANGLE(zgemm, ZGEMM)(const char *transa,
      | 
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:298:6: note: type mismatch in parameter 1
  298 | void BLAS_ZGEMM (char *transa, char *transb, BLAS_INT *m, BLAS_INT *n,
      |      ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:298:6: note: type 'char' should match type 'const char'
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:298:6: note: 'zgemm_' was previously declared here
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:298:6: note: code may be misoptimized unless '-fno-strict-aliasing' is used
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/include/deal.II/lac/lapack_templates.h:361: warning: 'dgemv_' violates the C++ One Definition Rule [-Wodr]
  361 |   void DEAL_II_FORTRAN_MANGLE(dgemv,
      | 
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:177:6: note: type mismatch in parameter 1
  177 | void BLAS_DGEMV (char *trans, BLAS_INT *m, BLAS_INT *n, double *alpha,
      |      ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:177:6: note: type 'char' should match type 'const char'
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:177:6: note: 'dgemv_' was previously declared here
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/include/deal.II/lac/lapack_templates.h:306: warning: 'dgemm_' violates the C++ One Definition Rule [-Wodr]
  306 |   void DEAL_II_FORTRAN_MANGLE(dgemm, DGEMM)(const char *transa,
      | 
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:279:6: note: type mismatch in parameter 1
  279 | void BLAS_DGEMM (char *transa, char *transb, BLAS_INT *m, BLAS_INT *n,
      |      ^
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:279:6: note: type 'char' should match type 'const char'
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/umfpack/UMFPACK/Source/cholmod_blas.h:279:6: note: 'dgemm_' was previously declared here
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/tbb-2018_U2/src/../include/tbb/task.h:582: warning: type 'tbb::task::state_type' violates the C++ One Definition Rule [-Wodr]
  582 |     enum state_type {
      | 
/raid/bangerth/p/deal.II/1/dealii/bundled/tbb-2018_U2/include/tbb/task.h:582: note: an enum with different number of values is defined in another translation unit
  582 |     enum state_type {
      | 
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/tbb-2018_U2/src/../include/tbb/tbb_exception.h:68: warning: type 'tbb::internal::exception_id' violates the C++ One Definition Rule [-Wodr]
   68 | enum exception_id {
      | 
/raid/bangerth/p/deal.II/1/dealii/bundled/tbb-2018_U2/include/tbb/tbb_exception.h:68: note: an enum with different value name is defined in another translation unit
   68 | enum exception_id {
      | 
/tempest/a/accounts/bangerth/p/deal.II/1/dealii/bundled/tbb-2018_U2/src/../include/tbb/tbb_exception.h:91: note: name 'eid_blocking_thread_join_impossible' differs from name 'eid_bad_tagged_msg_cast' defined in another translation unit
   91 |     eid_blocking_thread_join_impossible = eid_reserved1,
      | 
/raid/bangerth/p/deal.II/1/dealii/bundled/tbb-2018_U2/include/tbb/tbb_exception.h:93: note: mismatching definition
   93 |     eid_bad_tagged_msg_cast,
      | 
/usr/include/c++/12/bits/stl_heap.h: In function '__adjust_heap':
/usr/include/c++/12/bits/stl_heap.h:224: note: the ABI of passing structure with 'complex float' member has changed in GCC 4.4
  224 |     __adjust_heap(_RandomAccessIterator __first, _Distance __holeIndex,
      | 
```
Some of these we should probably address, though I'm unsure what to do about the TBB ones.

Perhaps not surprisingly, the result then segfaults:
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff00679b2 in tbb::interface9::global_control::active_value(int) () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
(gdb) bt
#0  0x00007ffff00679b2 in tbb::interface9::global_control::active_value(int) () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
#1  0x00007ffff00755fa in tbb::internal::market::global_market(bool, unsigned int, unsigned long) () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
#2  0x00007ffff00757fc in tbb::internal::market::create_arena(int, int, unsigned long) () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
#3  0x00007ffff0078308 in tbb::internal::governor::init_scheduler(int, unsigned long, bool) () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
#4  0x00007ffff0078b6b in tbb::task_scheduler_init::initialize(int, unsigned long) () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
#5  0x00007ffff61157ea in dealii::MultithreadInfo::set_thread_limit(unsigned int) () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
#6  0x00007fffe8fcdfa7 in __pthread_once_slow (once_control=0x7ffff7faf7a8 <dealii::MultithreadInfo::initialize_multithreading()::is_initialized>, init_routine=0x7fffe92d3200 <__once_proxy>) at ./nptl/pthread_once.c:116
#7  0x00007ffff60a15e4 in dealii::MultithreadInfo::initialize_multithreading() () from /tempest/a/accounts/bangerth/p/deal.II/1/install/lib/libdeal_II.so.9.7.0-pre
```

**Comment by bangerth** [comment]
I can report that if I switch on TaskFlow and switch off TBB, that things actually work.

**Comment by drwells** [comment]
Since we don't bundle TBB any more I don't think its possible for this error to show up any more, and we support LTO as of #17793.
