### ISSUE TITLE
MPI error with lac/vector_reinit_02

### ISSUE THREAD

**Issue by bangerth** [dealii/dealii#3515]
#3514 pointed at an issue in one of our tests that I don't understand because it's deep in the internals of the Trilinos wrappers. @kronbichler / @Rombur , could I ask for your help with this one?

Specifically, with the following patch
```
--- a/include/deal.II/base/mpi.templates.h
+++ b/include/deal.II/base/mpi.templates.h
@@ -95,6 +95,7 @@ namespace Utilities
 #ifdef DEAL_II_WITH_MPI
         if (job_supports_mpi())
           {
+               int err =
             MPI_Allreduce (values != output
                            ?
                            // TODO This const_cast is only needed for older
@@ -110,6 +111,16 @@ namespace Utilities
                            internal::mpi_type_id(values),
                            mpi_op,
                            mpi_communicator);
+               if (err != 0)
+               {
+                       int x;
+                       MPI_Error_class(err,&x);
+                       std::cout << "**************** " << x
+                                       << ' '
+                                               << MPI_ERR_COMM
+                                       << std::endl;
+               }
+               Assert (err==0, ExcInternalError());
           }
         else
 #endif
```
I get this kind of output from ` lac/vector_reinit_02`:
```
**************** 5 5
```
and the program subsequently aborts. This seems to suggest that we are using an invalid communicator for the reduction. The logic with which communicator is used is a bit beyond me, so I could use some help :-(

For reference, here is my backtrace:
```
#4  0x00007ffff4e508f2 in dealii::Utilities::MPI::internal::all_reduce<unsigned long long> (mpi_op=@0x7fffffffcfd8: 0x7fffdedd4f60 <ompi_mpi_op_sum>, values=values@entry=0x7fffffffd778, mpi_communicator=@0x7fffffffd000: 0x7a6830, output=output@entry=0x7fffffffcfb8, size=size@entry=1) at /home/fac/f/bangerth/p/deal.II/1/dealii/include/deal.II/base/mpi.templates.h:123
#5  0x00007ffff4e51ed6 in dealii::Utilities::MPI::internal::all_reduce<unsigned long long> (mpi_op=@0x7fffffffcfd8: 0x7fffdedd4f60 <ompi_mpi_op_sum>, t=@0x7fffffffd778: 5, mpi_communicator=@0x7fffffffd000: 0x7a6830) at /home/fac/f/bangerth/p/deal.II/1/dealii/include/deal.II/base/mpi.templates.h:178
#6  0x00007ffff4e51f03 in dealii::Utilities::MPI::sum<unsigned long long> (t=@0x7fffffffd778: 5, mpi_communicator=@0x7fffffffd000: 0x7a6830) at /home/fac/f/bangerth/p/deal.II/1/dealii/include/deal.II/base/mpi.templates.h:210
#7  0x00007ffff4ce8aad in dealii::TrilinosWrappers::MPI::Vector::reinit (this=this@entry=0x7fffffffda30, v=..., omit_zeroing_entries=omit_zeroing_entries@entry=false, allow_different_maps=allow_different_maps@entry=true) at /home/fac/f/bangerth/p/deal.II/1/dealii/source/lac/trilinos_vector.cc:366
#8  0x00007ffff4ce9311 in dealii::TrilinosWrappers::MPI::Vector::operator= (this=this@entry=0x7fffffffda30, v=...) at /home/fac/f/bangerth/p/deal.II/1/dealii/source/lac/trilinos_vector.cc:528
#9  0x0000000000414d82 in do_test<dealii::TrilinosWrappers::MPI::Vector> () at /home/fac/f/bangerth/p/deal.II/1/dealii/tests/lac/vector_reinit_02.cc:62
```

**Comment by bangerth** [comment]
If it makes a difference, this is in 64-bit mode.

**Comment by Rombur** [comment]
I will look into this some time next week.

**Comment by Rombur** [comment]
@bangerth has this been fixed? It works fine on my computer.

**Comment by bangerth** [comment]
I don't recall the details, but I think this was fixed.
