### ISSUE TITLE
boost 1.68.0 fails serialization configure check

### ISSUE THREAD

**Issue by davydden** [dealii/dealii#7074]
subj. At least with Intel 18.03 compilers. I will try GCC now...

EDIT: gcc 7.3.0 has no issues with boost 1.68.0

**Comment by davydden** [comment]
our sysadmin came across this issue with GCC. I will ask him to provide more details here.

**Comment by masterleinad** [comment]
I can reproduce with `gcc-8.1.0`:
```
Program received signal SIGSEGV, Segmentation fault.
std::_Rb_tree_rebalance_for_erase (__z=0x43ed40, __header=...) at ../../../.././libstdc++-v3/src/c++98/tree.cc:370
b370		      if (__w->_M_color == _S_red) 
(gdb) bt
#0  std::_Rb_tree_rebalance_for_erase (__z=0x43ed40, __header=...) at ../../../.././libstdc++-v3/src/c++98/tree.cc:370
#1  0x00007ffff7bb43a7 in boost::serialization::extended_type_info::key_unregister() const () from /mnt/data/darndt/boost-1.68.0/lib/libboost_serialization.so.1.68.0
#2  0x000000000041ce9e in boost::serialization::extended_type_info_no_rtti<polymorphic_base>::~extended_type_info_no_rtti (this=0x42c120 <boost::serialization::singleton<boost::serialization::extended_type_info_no_rtti<polymorphic_base> >::get_instance()::t>, 
    __in_chrg=<optimized out>) at /mnt/data/darndt/boost-1.68.0/include/boost/serialization/extended_type_info_no_rtti.hpp:107
#3  0x000000000041cabe in boost::serialization::singleton<boost::serialization::extended_type_info_no_rtti<polymorphic_base> >::get_instance()::singleton_wrapper::~singleton_wrapper() (
    this=0x42c120 <boost::serialization::singleton<boost::serialization::extended_type_info_no_rtti<polymorphic_base> >::get_instance()::t>, __in_chrg=<optimized out>) at /mnt/data/darndt/boost-1.68.0/include/boost/serialization/singleton.hpp:121
#4  0x00007ffff7270ff8 in ?? () from /lib/x86_64-linux-gnu/libc.so.6
#5  0x00007ffff7271045 in exit () from /lib/x86_64-linux-gnu/libc.so.6
#6  0x00007ffff7257837 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#7  0x000000000041b5f9 in _start ()
```

**Comment by masterleinad** [comment]
I only followed the discussion loosely in the last few month, but thought they have figured it out finally. I need to check if the current developer version works...

**Comment by davydden** [comment]
> but thought they have figured it out finally

It looks like there is https://github.com/boostorg/serialization/pull/105 but it's not merged. Last activity June 25.

**Comment by davydden** [comment]
I adapted boostorg/serialization#105 to be a patch for 1.68.0 [boost_1.68.0.zip](https://github.com/dealii/dealii/files/2302992/boost_1.68.0.zip) and try this now...

**Comment by masterleinad** [comment]
We can't do anything about it here, so let's close.
