### ISSUE TITLE
bug in 64bit epetra :SparsityPattern::compress

### ISSUE THREAD

**Issue by tjhei** [dealii/dealii#8377]
I using epetra with 64 bit indices (you can try step-32 with 2 ranks for example).
Trilinos throws the following char exception:
```
    int  NumGlobalElements() const {                                                                                                                
      if(GlobalIndicesInt())                                                                                                              
         return (int) NumGlobalElements64();                                                                                               
         throw "Epetra_BlockMap::NumGlobalElements: GlobalIndices not int.";                                                                 
       }                                  
```
 Call stack:
```
#0  0x00007fffdac648bd in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#1  0x00007ffff013e08d in Epetra_BlockMap::NumGlobalElements (this=0x1110620)
    at /ssd/candi-v9.0.1-r6/trilinos-release-12-10-1/include/Epetra_BlockMap.h:549
#2  0x00007ffff01379ed in dealii::TrilinosWrappers::SparsityPattern::compress (this=0x11119a0)
    at /ssd/deal-git/source/lac/trilinos_sparsity_pattern.cc:795
#3  0x00007fffefb031f1 in dealii::BlockSparsityPatternBase<dealii::TrilinosWrappers::SparsityPattern>::compress (this=0x7fffffff9e00)
    at /ssd/deal-git/source/lac/block_sparsity_pattern.cc:172
#4  0x00000000007052c9 in Step32::BoussinesqFlowProblem<2>::setup_stokes_matrix (this=0x7fffffffac40,
    stokes_partitioning=std::vector of length 2, capacity 2 = {...}, stokes_relevant_partitioning=std::vector of length 2, capacity 2 = {...})
    at /ssd/deal-git/examples/step-32/step-32.cc:1732
#5  0x00000000006fb958 in Step32::BoussinesqFlowProblem<2>::setup_dofs (this=0x7fffffffac40) at /ssd/deal-git/examples/step-32/step-32.cc:1976
#6  0x00000000006f4397 in Step32::BoussinesqFlowProblem<2>::run (this=0x7fffffffac40) at /ssd/deal-git/examples/step-32/step-32.cc:3434
#7  0x00000000006d8b52 in main (argc=1, argv=0x7fffffffd4a8) at /ssd/deal-git/examples/step-32/step-32.cc:3602
```

I am working on a fix...

**Comment by tjhei** [comment]
see #8378
